
export const houses = [
  {
    id: 1,
    title: 'Urban Tuplis 10th Floor',
    location: 'L.B Nagar ,Hyderabad ,500079',
    image: '/images/img6.jpeg',
    description: `This well-maintained 2BHK apartment located at  L.B Nagar ,Hyderabad ,500079. With a built-up area of 1600 Sq Ft, the home offers spacious 2 bedrooms, two modern bathrooms, 
                a semi-furnished modular kitchen, and a scenic road-facing balcony. Positioned on the 10th floor of a 5-storey building, the apartment receives ample natural light and ventilation throughout the day.
                The property is 5 years old and part of a secure, gated society that offers 24x7 security, lift access, power backup, and dedicated parking. It is ideal for small families or working professionals, offering 
                excellent connectivity to tech parks, hospitals, schools, and metro stations. With a monthly rent of ₹15,000 and a refundable deposit of ₹1,50,000, this home strikes the perfect balance between comfort, convenience, and affordability.`,
    beds: 2,
    size: '1600 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 15000,
    discount: '15% OFF for 1st 3 months',
    deposit: '15000',
    bathrooms: 2,
    parking: 1,
    floor: '10th',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: '24/7 Security',
    powerBackup: 'Yes',
    propertyAge: 5,
    waterSupply: 'Borewell + Corporation',
    facing: 'East Facing',
    balcony: '2 (Road-facing)',
    nearbyLocation: 'HSR Layout, Bangalore',
    nearbyMetro: 'HSR Metro Station - 1.5 km',
    nearbyMall: 'Forum Mall - 3 km',
    mapImage: '/images/map.png',
  },

  {
    id: 2,
    title: 'Tuplis 12th Floor',
    location: 'S.R Nagar ,Hyderabad ,50089',
    image: '/images/img2.jpeg',
    description: `This well-maintained 2BHK apartment located at  'S.R Nagar ,Hyderabad ,50089  With a built-up area of 1800 Sq Ft, the home offers spacious 2 bedrooms, two modern bathrooms, a semi-furnished modular kitchen, 
                and a scenic road-facing balcony. Positioned on the 12th floor of a 5-storey building, the apartment receives ample natural light and ventilation throughout the day.
                The property is 5 years old and part of a secure, gated society that offers 24x7 security, lift access, power backup, and dedicated parking. It is ideal for small families or working professionals, 
                offering excellent connectivity to tech parks, hospitals, schools, and metro stations. With a monthly rent of ₹16,000 and a refundable deposit of ₹1,50,000, this home strikes the perfect balance between comfort, convenience, and affordability.`,
    beds: 2,
    size: '1800 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 16000,
    discount: '15% OFF for 1st 3 months',
    deposit: '15000',
    bathrooms: 2,
    parking: 1,
    floor: '10th',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: '24/7 Security',
    powerBackup: 'Yes',
    propertyAge: 5,
    waterSupply: 'Borewell + Corporation',
    facing: 'East Facing',
    balcony: '2 (Road-facing)',
    nearbyLocation: 'HSR Layout, Bangalore',
    nearbyMetro: 'HSR Metro Station - 1.5 km',
    nearbyMall: 'Forum Mall - 3 km',
    mapImage: '/images/map.png',
  },
  {
    id: 3,
    title: 'Avanthi Hills 5th Floor',
    location: 'BalaNagar ,Hyderabad ,500071',
    image: '/images/img3.jpeg',
    description: `This well-maintained 2BHK apartment located BalaNagar ,Hyderabad ,500071'  With a built-up area of 1400 Sq Ft, the home offers spacious 2 bedrooms, two modern bathrooms, a semi-furnished modular kitchen, 
          and a scenic road-facing balcony. Positioned on the 5th floor of a 5-storey building, the apartment receives ample natural light and ventilation throughout the day.The property is 5 years old and part of a secure, gated
          society that offers 24x7 security, lift access, power backup, and dedicated parking. It is ideal for small families or working professionals, offering excellent connectivity to tech parks, hospitals, schools, and metro 
          stations. With a monthly rent of ₹12,000 and a refundable deposit of ₹1,50,000, this home strikes the perfect balance between comfort, convenience, and affordability.`,
    beds: 2,
    size: '1400 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 12000,
    discount: '15% OFF for 1st 3 months',
    deposit: '15000',
    bathrooms: 2,
    parking: 1,
    floor: '10th',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: '24/7 Security',
    powerBackup: 'Yes',
    propertyAge: 5,
    waterSupply: 'Borewell + Corporation',
    facing: 'East Facing',
    balcony: '2 (Road-facing)',
    nearbyLocation: 'HSR Layout, Bangalore',
    nearbyMetro: 'HSR Metro Station - 1.5 km',
    nearbyMall: 'Forum Mall - 3 km',
    mapImage: '/images/map.png',

  },
  {
    id: 4,
    title: 'Vassavi Estate 2nd Floor',
    location: 'R.N.Reddy ,Hyderabad ,500079',
    image: '/images/img4.jpg',
    description: `This well-maintained 2BHK apartment located at  'R.N.Reddy ,Hyderabad ,500079' With a built-up area of 1600 Sq Ft, 
          the home offers spacious 2 bedrooms, two modern bathrooms, a semi-furnished modular kitchen, and a scenic road-facing balcony.
          Positioned on the 2nd floor of a 5-storey building, the apartment receives ample natural light and ventilation throughout the day.
          The property is 5 years old and part of a secure, gated society that offers 24x7 security, lift access, power backup, and dedicated parking. 
          It is ideal for small families or working professionals, offering excellent connectivity to tech parks, hospitals, schools, and metro stations. 
          With a monthly rent of ₹10,000 and a refundable deposit of ₹1,50,000, this home strikes the perfect balance between comfort, convenience,and affordability.`,
    beds: 2,
    size: '1600 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 10000,
    discount: '15% OFF for 1st 3 months',
    deposit: '15000',
    bathrooms: 2,
    parking: 1,
    floor: '10th',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: '24/7 Security',
    powerBackup: 'Yes',
    propertyAge: 5,
    waterSupply: 'Borewell + Corporation',
    facing: 'East Facing',
    balcony: '2 (Road-facing)',
    nearbyLocation: 'HSR Layout, Bangalore',
    nearbyMetro: 'HSR Metro Station - 1.5 km',
    nearbyMall: 'Forum Mall - 3 km',
    mapImage: '/images/map.png',
  },
  {
    id: 5,
    title: 'Sun City My Homes 10th Floor',
    location: 'ShadNagar ,Hyderabad ,500079',
    image: '/images/img5.jpg',
    description: `This well-maintained 2BHK apartment located at  'Shad Nagar , Hyderabad ,500079' With a built-up area of 1600 Sq Ft, 
                  the home offers spacious 2 bedrooms, two modern bathrooms, a semi-furnished modular kitchen, and a scenic road-facing balcony. 
                  Positioned on the 10th  floor of a 5-storey building, the apartment receives ample natural light and ventilation throughout 
                  the day.The property is 5 years old and part of a secure, gated society that offers 24x7 security, lift access, power backup,
                  and dedicated parking. It is ideal for small families or working professionals, offering excellent connectivity to tech parks,
                    hospitals, schools, and metro stations. With a monthly rent of ₹20,000 and a refundable deposit of ₹1,50,000, this home strikes
                    the perfect balance between comfort, convenience, and affordability.`,
    beds: 2,
    size: '1600 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 20000,
    discount: '15% OFF for 1st 3 months',
    deposit: '15000',
    bathrooms: 2,
    parking: 1,
    floor: '10th',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: '24/7 Security',
    powerBackup: 'Yes',
    propertyAge: 5,
    waterSupply: 'Borewell + Corporation',
    facing: 'East Facing',
    balcony: '2 (Road-facing)',
    nearbyLocation: 'HSR Layout, Bangalore',
    nearbyMetro: 'HSR Metro Station - 1.5 km',
    nearbyMall: 'Forum Mall - 3 km',
    mapImage: '/images/map.png',
  },

  {
    id: 6,
    title: 'City Homes 1st Floor',
    location: 'Madhapur,Hyderabad ,500089',
    image: '/images/img5.jpg',
    description: `This well-maintained 2BHK apartment located at  'Shad Nagar , Hyderabad ,500079' With a built-up area of 1600 Sq Ft, 
                the home offers spacious 2 bedrooms, two modern bathrooms, a semi-furnished modular kitchen, and a scenic road-facing balcony.
                Positioned on the 10th  floor of a 5-storey building, the apartment receives ample natural light and ventilation throughout the day.
                  The property is 5 years old and part of a secure, gated society that offers 24x7 security, lift access, power backup, and dedicated parking. 
                  It is ideal for small families or working professionals, offering excellent connectivity to tech parks, hospitals, schools, and metro stations. 
                  With a monthly rent of ₹20,000 and a refundable deposit of ₹1,50,000, this home strikes the perfect balance between comfort, convenience, and affordability.`,
    beds: 2,
    size: '1600 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 20000,
    discount: '15% OFF for 1st 3 months',
    deposit: '15000',
    bathrooms: 2,
    parking: 1,
    floor: '10th',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: '24/7 Security',
    powerBackup: 'Yes',
    propertyAge: 5,
    waterSupply: 'Borewell + Corporation',
    facing: 'East Facing',
    balcony: '2 (Road-facing)',
    nearbyLocation: 'HSR Layout, Bangalore',
    nearbyMetro: 'HSR Metro Station - 1.5 km',
    nearbyMall: 'Forum Mall - 3 km',
    mapImage: '/images/map.png',
  },
  {
    id: 7,
    title: 'My Homes 2nd Floor',
    location: 'Hi-Tech City,Hyderabad ,500779',
    image: '/images/img5.jpg',
    description: `This well-maintained 2BHK apartment located 'Hi-Tech City,Hyderabad ,500779' With a built-up area of 1600 Sq Ft, 
                the home offers spacious 2 bedrooms, two modern bathrooms, a semi-furnished modular kitchen, and a scenic road-facing balcony. 
                  Positioned on the 2nd floor of a 5-storey building, the apartment receives ample natural light and ventilation throughout the day.
                  The property is 5 years old and part of a secure, gated society that offers 24x7 security, lift access, power backup, and dedicated parking. 
                  It is ideal for small families or working professionals, offering excellent connectivity to tech parks, hospitals, schools,
                  and metro stations. With a monthly rent of ₹60,000 and a refundable deposit of ₹1,50,000, this home strikes the perfect balance between 
                  comfort, convenience, and affordability.`,
    beds: 2,
    size: '1800 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 60000,
    discount: '15% OFF for 1st 3 months',
    deposit: '15000',
    bathrooms: 2,
    parking: 1,
    floor: '10th',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: '24/7 Security',
    powerBackup: 'Yes',
    propertyAge: 5,
    waterSupply: 'Borewell + Corporation',
    facing: 'East Facing',
    balcony: '2 (Road-facing)',
    nearbyLocation: 'HSR Layout, Bangalore',
    nearbyMetro: 'HSR Metro Station - 1.5 km',
    nearbyMall: 'Forum Mall - 3 km',
    mapImage: '/images/map.png',
  },
];
