export const houses = [
  {
    id: 1,
    agentId: 1,
    title: '1 BHK Independent House for Rent' ,
    location: 'Allwyn Colony, Kukatpally, Hyderabad,500072',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946124/1_10_whadnh.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946124/1_12_ce7bn1.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946123/1_5_wilwfk.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946123/1_13_p1ycsu.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946124/1_11_hlnxhl.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946124/14_sab0wt.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946125/18_pkwji4.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946125/1_7_hxnp9s.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946125/1_9_rwsrnl.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946125/1_2_a4ka4l.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946125/1_6_ymnuld.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946126/1_1_r4t7ao.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757946124/1_10_whadnh.avif',

    ],
    description: 'This is a well-designed 1 BHK Independent House available for rent. It is situated in a prime location of Hyderabad at Jagadgiri Gutta. This modern Independent House is Fully Furnished. The 1 BHK unit fulfills all the needs of a modern lifestyle for families. This unit is on 0 floor. The Independent House provides complete comfort for the residents. The Independent House lets you enjoy the lush greenery around. Meticulously designed to meet your housing needs, this unit has 1 bedroom and 1 bathroom. It includes 1 balcony allowing residents to catch a glimpse of the city’s skyline. This rented Independent House has been developed as South facing in compliance with Vastu principles. The carpet area is 650.0 Square feet. The total built-up area is 750 Square feet. The total monthly rent is Rs 18000. The security deposit payable is Rs 36000.',
    size: '750 sq.ft',
    beds: 1,
    price: '18,000',
    deposit: '36,000',
    bathrooms: 1,
    parking: '1 open',
    floor: 'ground ',
    furnishing: 'fully-Furnished',
    propertyType: 'independent house',
    propertyAge: 8,
    facing: 'south Facing',
    balcony: '1 balcony',
    powerBackup: 'NA',
    lift: 'NA',
    waterSupply: '24/7 water supply',
    security: 'cctv cameras',
    nearbyLocation: 'Harsha Hospital Best Obstetrician Gynecologist Kukatpally',
    nearbyMetro: 'KPHB Metro station',
    nearbyMall: 'Forum Sujana Mall',
    latitude: '17.50661970717292',
    longitude: '78.41123539219119',
    discount: '5% off on annual rent',
  },

  {
    id: 2,
    agentId: 4,
    title: '1 BHK Flat for Rent',
    location: 'SvS con, Police Colony, Kondapur, Hyderabad,500084',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951519/2_8_qrnldr.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951519/2_7_hvczoh.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951520/2_4_y92zxj.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951520/2_5_manrpr.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951520/2_6_yxqhpt.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951520/2_9_i1kicm.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951521/2_3_xdmxgz.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951521/2_1_tcexmz.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951521/2_1_tcexmz.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951522/2_2_lherip.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757951521/2_3_xdmxgz.avif',
      
    ],
    description:'This Flat can be a comfortable and affordable home for your family. It is a 1 BHK unit available on rent at Kondapur in Hyderabad. This Flat comes with a plethora of amenities to meet your modern lifestyle needs. It is semi furnished. It is located on floor 2 of the building having a total 6 floors. Offering beautiful city views, this 1 BHK has been thoughtfully developed. It includes a total of 1 bedroom and 1 bathroom. It also includes 1 balcony that can be a perfect place for relaxation. The built-up area of the Flat is 800 square_feet. The Flat is available for a monthly rent of Rs 16055. The security deposit payable is Rs 16055.',
    beds: 1,
    size: '800 Sq Ft',
    type: 'Flat',
    price: '16,055',
    deposit: '16,055',
    bathrooms: 1,
    parking: 'NA',
    floor: '2nd ',
    balcony: '1',
    furnishing: 'UnFurnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'NA',
    propertyAge: 0,
    waterSupply: 'Regular',
    nearbyLocation: 'KIMS Hospitals Kondapur, KIMS Cuddles',
    nearbyMetro: 'Raidurg metro station',
    nearbyMall: 'sarath city mall',
    latitude: '17.464337227761515',
    longitude: '78.36194267838076',
    discount: '5% off on annual rent',
  },

  {
    id: 3,
    agentId: 1,
    title: '1 BHK Flat for Rent',
    location: 'Un mode, Kondapur, Hyderabad,500084',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953218/3_8_r2upxh.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953218/3_10_pbtmut.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953218/3_11_nvg5vc.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953218/3_9_eccypn.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953220/3_5_hyhcqu.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953219/3_7_onbwle.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953220/3_6_mx3jki.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953221/3_3_fhls9a.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953221/3_4_tngbmx.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953222/3_2_m0tag9.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757953223/3_1_lvydvw.avif',
      
    ],
    description: 'This is a modern and stylish home available for affordable rent in Hyderabad. It is a 1 BHK Flat situated at Kondapur. Designed to meet your lifestyle needs, the Flat provides a range of modern amenities for the comfort of the residents. It is fully furnished. Modern home seekers will experience a comfortable living in this 1 BHK property. The Flat is on 2 floor, and the total number of floors is 5. The 1 BHK unit is elegantly designed to meet your housing needs. The Flat has 1 bedroom. It has 1 bathroom. The 1 BHK unit also includes 1 balcony giving splendid views of the surroundings. It is a North facing unit, designed as per Vastu principles. The built-up area of the Flat is 550 square_feet. The monthly rent for the Flat is Rs 24005. The security deposit is Rs 48010.',
    beds: 1,
    size: '550 Sq Ft',
    type: 'Flat',
    price: '24,005',
    deposit: '48010',
    bathrooms: 1,
    parking: '1 open + 1 covered',
    floor: '2nd ',
    balcony: '1',
    furnishing: 'Fully-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'Available',
    facing: 'North Facing',
    propertyAge: 1,
    waterSupply: 'Regular',
    nearbyLocation: 'KIMS Hospitals Kondapur, KIMS Cuddles',
    nearbyMetro: 'Raidurg metro station',
    nearbyMall: 'sarath city mall',
    latitude: '17.462381827026984',
    longitude: '78.35184819047576',
    discount: '7% off on annual rent',
  },
  {
    id: 4,
    agentId: 2,
    title: '1 BHK Flat for Rent',
    location: 'Raghavendra Colony, Kondapur, Hyderabad,500084',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757954607/4_1_zoyvrb.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757954606/4_3_l2mdue.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757954606/4_2_gewtm8.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757954606/4_5_yul7sx.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757954605/4_6_d4kzkw.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757954605/4_4_mquexq.avif',
      
    ],
    description: 'Check out this Flat available for rent in Kondapur in Hyderabad. It is a 1 BHK unit that comes at an affordable rent, with modern features and premium amenities to suit your lifestyle needs. The unit is unfurnished. With numerous new-age amenities and green surroundings, this Flat provides a convenient lifestyle for residents. A spacious house for your family, this unit includes 1 bedroom. There are 1 bathroom and 1 balcony. It has a built-up area of 800 square_feet. The carpet area is 700.0 square_feet. The Flat is built on 1 floor. The building has a total of 6 floors. The monthly rent is Rs 16000 and the security deposit to be paid by residents is Rs 32000.',
    beds: 1,
    size: '800 Sq Ft',
    type: 'Flat',
    price: '16,000',
    deposit: '32,000',
    bathrooms: 1,
    parking: '1 open + 1 covered',
    floor: '1st',
    balcony: '1',
    furnishing: 'UnFurnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'NA',
    facing: 'North Facing',
    propertyAge: 1,
    waterSupply: 'Regular',
    nearbyLocation: 'Sanskriti School',
    nearbyMetro: 'Raidurg metro station',
    nearbyMall: 'sarath city mall',
    latitude: '17.471934572176963', 
    longitude:'78.3601016032763',
    discount: '8% off on annual rent',
  },

  {
    id: 5,
    agentId: 1,
    title: '1 BHK Flat for Rent',
    location: 'Ravika house, Siddhi Vinayak Nagar, Madhapur, Hyderabad,500081',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955834/5_6_p2mfsl.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955835/5_5_ondogs.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955833/5_7_z1inqg.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955833/5_9_mqquui.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955833/5_8_pukmy7.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955839/5_1_qg7r33.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955837/5_3_bfhw7a.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955838/5_2_cuk0n2.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955836/5_4_wdh77x.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757955836/5_4_wdh77x.avif',
     
    ],
    description: 'Check this beautiful 1 BHK Flat available for rent in Hyderabad. Nestled at a prime location in Madhapur, it is an ideal home for those looking for a modern lifestyle. The Flat is fully furnished, available for affordable rent. This 1 BHK unit is inside a gated society equipped with various amenities and ample greenery. The Flat is thoughtfully designed to ensure a comfortable living. It includes 1 bedroom and 1 bathroom. Out of a total 7 floors, this 1 BHK unit is built on floor 4. It also has 1 balcony that have been spaciously designed and allow you to enjoy the magnificent views of the surroundings. The Flat is Vastu-compliant and designed as East facing house. The carpet area of this property is 800 square_feet. The built-up area is 850 square_feet. The monthly rent for this Flat is Rs 25000, and the security deposit is Rs 50000.',
    beds: 1,
    size: '850 Sq Ft',
    type: 'Flat',
    price: '25,000',
    deposit: '50,000',
    bathrooms: 1,
    parking: '1 open + 1 covered',
    floor: '4th',
    balcony: '1',
    furnishing: 'Fully-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'Available',
    facing: 'East Facing',
    propertyAge: 0,
    waterSupply: 'Regular',
    nearbyLocation: 'Meridian School - Madhapur',
    nearbyMetro: 'Madhapur metro station',
    nearbyMall: 'Inorbit Mall ',
    latitude: '17.4593735431695',
    longitude: '78.38811805384806',
    discount: '10% off on annual rent',
  },

  {
    id: 6,
    agentId: 5, 
    title: '1 BHK Flat for Rent',
    location: 'Dream home, Chanda Naik Nagar, Madhapur, Hyderabad,500081',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757956973/6_5_jppozh.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757956973/6_6_s8rzbi.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757956975/6_4_ps7abn.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757956975/6_3_e0qn3b.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757956977/6_1_by95sk.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757956976/6_2_jlgmfr.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757956973/6_5_jppozh.avif',
    ],
    description: `This Flat can be a comfortable and affordable home for your family. It is a 1 BHK unit available on rent at Madhapur in Hyderabad. This Flat comes with a plethora of amenities to meet your modern lifestyle needs. It is unfurnished. It is located on floor 1 of the building having a total 7 floors. Offering beautiful city views, this 1 BHK has been thoughtfully developed. It includes a total of 1 bedroom and 1 bathroom. The property is East facing. It also includes 1 balcony that can be a perfect place for relaxation. The built-up area of the Flat is 650 square_feet. The carpet area is 600.0 square_feet. The Flat is available for a monthly rent of Rs 15500. The security deposit payable is Rs 31000.`,
    beds: 1,
    size: '650 Sq Ft',
    type: 'Flat',
    price: '15,500',
    deposit: '31,000',
    bathrooms: 1,
    parking: '1 open ',
    floor: '1st',
    balcony: '1',
    furnishing: 'UnFurnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'NA',
    acing: 'East Facing',
    propertyAge: 3,
    waterSupply: 'Regular',
    nearbyLocation: 'Yashoda Hospitals Hitech City',
    earbyMetro: 'Madhapur metro station',
    nearbyMall: 'City Centre Mall ',
    latitude: '17.455172783415172',
    longitude:'78.3925093690634',
    discount: '5% off on annual rent',
},
{
    id: 7,
    agentId: 6, 
    title: '2 BHK Flat for Rent',
    location: 'Madhapur 100 feet road, Chanda Naik Nagar, Madhapur, Hyderabad,500081',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757958125/7_4_pvywdw.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757958122/7_8_znp0z1.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757958123/7_6_enttha.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757958123/7_5_bodg6l.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757958125/7_4_pvywdw.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757958126/7_3_bxiume.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757958127/7_2_v78xuh.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757958129/7_1_uo7ojw.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757958122/7_8_znp0z1.avif',
    ],
    description: `This is a well-designed 2 BHK Flat available for rent. It is situated in a prime location of Hyderabad at Madhapur. This modern Flat is semi furnished. The 2 BHK unit fulfills all the needs of a modern lifestyle for families. There is a total of 6 floors. This unit is on 3 floor. The Flat provides complete comfort for the residents. The Flat lets you enjoy the lush greenery around. Meticulously designed to meet your housing needs, this unit has 2 bedrooms and 2 bathroom. It includes 1 balcony allowing residents to catch a glimpse of the city’s skyline. The carpet area is 1107.0 square_feet. The total built-up area is 1207 square_feet. The total monthly rent is Rs 30000. The security deposit payable is Rs 60000.`,
    beds: 2,
    size: '1207 Sq Ft',
    type: 'Flat',
    price: '30,000',
    deposit: '60,000',
    bathrooms: 2,
    parking: '1 open and 1 covered',
    floor: '3rd',
    balcony: '1',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'NA',
    powerBackup: 'NA',
    facing: 'West Facing',
    propertyAge: 3,
    waterSupply: 'Regular',
    nearbyLocation: 'Yashoda Hospitals Hitech City',
    nearbyMetro: 'Madhapur metro station',
    nearbyMall: 'City Centre Mall ',
    latitude:'17.452771709615984', 
    longitude:'78.39184851803778',
    discount: '9% off on annual rent',
},
{
    id: 8,
    agentId: 7, 
    title: '3 BHK Flat for Rent',
    location: 'Madhapur Ayyappa society, Mega Hills, Madhapur, Hyderabad,500081',
    image: [
        'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757959205/8_2_hhjpg5.avif',
        'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757959202/8_1_naxygw.avif',
        'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757959200/8_3_qaflni.avif',
        'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757959200/8_4_zpdazr.avif',
        'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757959198/8_6_te3ggu.avif',
        'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757959199/8_7_rpxhjn.avif',
        'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757959199/8_5_zixntn.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757959197/8_8_dpfyjq.avif',
    ],
    description: `Here is an excellent 3 BHK Flat available for rent in Hyderabad. Surrounded by natural greens and equipped with numerous amenities, this rented 3 BHK house offers a comfortable lifestyle for families. It is a spacious property nestled in Madhapur that enjoys good connectivity to major landmarks of the city. The Flat is on the 6 floor. There is a total of 7 floors. The Flat is designed as per modern construction standards. It has 3 bedrooms and 3 bathroom. It is East facing. The 3 BHK unit is thoughtfully designed to meet the space needs of a modern family and allows ample sunlight and fresh air. There are 3 balcony in this unit where residents can spend a relaxed evening and enjoy excellent views of the surroundings. This Flat has 1900 Square feet of built-up area. The monthly rent payable is Rs 45000, and the security deposit to be paid is Rs 90000.`,
    beds: 3,
    size: '1900 Sq Ft',
    type: 'Flat',
    price: '45,000',
    deposit: '90,000',
    bathrooms: 3,
    parking: '1 open and 1 covered',
    floor: '6th',
    balcony: '3',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'Available',
    facing: 'East Facing',
    propertyAge: 3,
    waterSupply: 'Regular',
    nearbyLocation: 'ORCHIDS The International School - CBSE School in Jubilee Hills',
    nearbyMetro: 'Madhapur metro station',
    nearbyMall: 'Amrutha Mall ',
    latitude:'17.44889532712224', 
    longitude:'78.39077605241059',
    discount: '15% off on annual rent',
},
{
    id: 9,
    agentId: 8, 
    title: '2 BHK Flat for Rent',
    location: 'Un mode, Gachibowli, Hyderabad,500032',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757996939/9_7_diajgm.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757996939/9_10_xf1h6o.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757996940/9_6_qdu5qh.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757996940/9_5_glr2yb.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757996940/9_2_kkfrzn.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757996940/9_8_k3hesp.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757996940/9_1_rvvubb.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757996940/9_4_unjhta.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1757996940/9_3_hhxymu.avif',

     
    ],
    description: `Here is an excellent 2 BHK Flat available for rent in Hyderabad. Surrounded by natural greens and equipped with numerous amenities, this rented 2 BHK house offers a comfortable lifestyle for families. It is a spacious property nestled in Gachibowli that enjoys good connectivity to major landmarks of the city. The Flat is on the 2 floor. There is a total of 5 floors. The Flat is designed as per modern construction standards. It has 2 bedrooms and 2 bathroom. It is East facing. The 2 BHK unit is thoughtfully designed to meet the space needs of a modern family and allows ample sunlight and fresh air. There are 1 balcony in this unit where residents can spend a relaxed evening and enjoy excellent views of the surroundings. This Flat has 1150 square_feet of built-up area. The monthly rent payable is Rs 32000, and the security deposit to be paid is Rs 64000.`,
    beds: 2,
    size: '1150 Sq Ft',
    type: 'Flat',
    price: '32,000',
    deposit: '64,000',
    bathrooms: 2,
    parking: '1 open and 1 covered',
    floor: '2nd',
    balcony: '1',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'Available',
    facing: 'East Facing',
    propertyAge: 1,
    waterSupply: 'Regular',
    nearbyLocation: 'Kendriya Vidyalaya, Gachibowli',
    nearbyMetro: 'Raidurg metro station',
    nearbyMall: 'Inorbit Mall ',
    latitude:'17.436225372459283',
    longitude:'78.33383047201573',
    discount: '6% off on annual rent',
},
{
    id: 10,
    agentId: 10, 
    title: '2 BHK Independent Builder Floor for Rent',
    location: 'Burugupalli Residency, Chhota Anjaiah Nagar, Gachibowli, Hyderabad,500032',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000094/10_1_obelsn.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000093/10_2_kd3du2.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000090/10_3_meenyr.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000089/10_4_tsao2u.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000087/10_5_pccncc.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000086/10_6_epka9z.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000084/10_7_pctfrl.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000083/10_8_l2xmzp.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000082/10_9_q5bmxd.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000082/10_10_lj5s3a.avif',
      
      
    ],
    description: `Here is an excellent 2 BHK Independent Floor available for rent in Hyderabad. Surrounded by natural greens and equipped with numerous amenities, this rented 2 BHK house offers a comfortable lifestyle for families. It is a spacious property nestled in Gachibowli that enjoys good connectivity to major landmarks of the city. The Independent Floor is on the 2 floor. There is a total of 5 floors. The Independent Floor is designed as per modern construction standards. It has 2 bedrooms and 2 bathroom. It is East facing. The 2 BHK unit is thoughtfully designed to meet the space needs of a modern family and allows ample sunlight and fresh air. There are 1 balcony in this unit where residents can spend a relaxed evening and enjoy excellent views of the surroundings. This Independent Floor has 1250 square_feet of built-up area. It has a carpet area of 1100 square_feet. The monthly rent payable is Rs 35000, and the security deposit to be paid is Rs 70000.`,
    beds: 2,
    size: '1250 Sq Ft',
    price: '35,000',
    deposit: '70,000',
    bathrooms: 2,
    parking: '1 open and 1 covered',
    floor: '2nd',
    balcony: '1',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'Available',
    facing: 'East Facing',
    propertyAge: 1,
    waterSupply: 'Regular',
    nearbyLocation: 'Himagiri Hospitals Gachibowli',
    nearbyMetro: 'Raidurg metro station',
    nearbyMall: 'Atrium Mall ',
    latitude:'17.445453895498257', 
    longitude:'78.35925962542133',
    discount: '12% off on annual rent',
  
},
{
    id: 11,
    agentId: 11, 
    title: '3 BHK Flat for Rent',
    location: 'Dukes Galaxy, Sri Ram Nagar Colony, Banjara Hills, Hyderabad,500034',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000229/11_1_mpfbij.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000221/11_2_eox5dy.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000215/11_3_s0tqe2.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000214/11_4_p4kqbz.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000210/11_5_e0mf8b.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000197/11_6_aahulp.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000197/11_6_aahulp.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000196/11_7_prcmnm.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000158/11_8_kbkoy9.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000154/11_9_ororqq.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000152/11_10_vo9lys.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000150/11_11_fbgtm9.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758000148/11_12_cpkkvs.avif',
      
    ],
    description: `Here is an excellent 3 BHK Flat available for rent in Hyderabad. Surrounded by natural greens and equipped with numerous amenities, this rented 3 BHK house offers a comfortable lifestyle for families. It is a spacious property nestled in Banjara Hills that enjoys good connectivity to major landmarks of the city. The Flat is on the 5 floor. There is a total of 10 floors. The Flat is designed as per modern construction standards. It has 3 bedrooms and 3 bathroom. It is North-East facing. The 3 BHK unit is thoughtfully designed to meet the space needs of a modern family and allows ample sunlight and fresh air. There are 0 balcony in this unit where residents can spend a relaxed evening and enjoy excellent views of the surroundings. This Flat has 2475 square feet of built-up area. It has a carpet area of 1980 square feet. The monthly rent payable is Rs 70007, and the security deposit to be paid is Rs 210000.`,
    beds: 3,
    size: '2475 Sq Ft',
    price: '70,000',
    deposit: '2.1 Lacs',
    bathrooms: 3,
    parking: ' 1 covered',
    floor: '5th',
    balcony: '1',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'Available',
    facing: 'North-East Facing',
    propertyAge: 6,
    waterSupply: '24/7 water supply',
    nearbyLocation: 'KIMS - Sunshine Hospitals, Begumpet',
    nearbyMetro: 'Khairatabad metro station',
    nearbyMall: 'GVK One Mall ',
    latitude:'17.409588643807634',
    longitude:'78.44706017939872',
    discount: '10% off on annual rent',
},
{
    id: 12,
    agentId: 13,
    title: '2 BHK Penthouse for Rent',
    location: 'Financial District, Hyderabad,500032',
    image: [
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758001361/12_7_c3tbck.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758001365/12_1_fu4ras.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758001364/12_2_ra6vro.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758001363/12_3_vrgufg.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758001362/12_4_zxvko9.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758001361/12_5_hdc43t.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758001361/12_6_xz1gbe.avif',
      'https://res.cloudinary.com/dvqrtjzvv/image/upload/v1758001361/12_7_c3tbck.avif',

    
    ],
    description: 'This is a well-designed 2 BHK Penthouse available for rent. It is situated in a prime location of Hyderabad at Nanakramguda. This modern Penthouse is semi furnished. The 2 BHK unit fulfills all the needs of a modern lifestyle for families. There is a total of 5 floors. This unit is on 5 floor. The Penthouse provides complete comfort for the residents. The Penthouse lets you enjoy the lush greenery around. Meticulously designed to meet your housing needs, this unit has 2 bedrooms and 2 bathroom. It includes 0 balcony allowing residents to catch a glimpse of the city’s skyline. The total built-up area is 1200 square_feet. The total monthly rent is Rs 28000. The security deposit payable is Rs 28000.',
    beds: 2,
    size: '1200 Sq Ft',
    price: '28,000',
    deposit: '28,000',
    bathrooms: 2,
    parking: '1 open and 1 covered',
    floor: '5th',
    balcony: 'NA',
    furnishing: 'Semi-Furnished',
    propertyType: 'Apartment',
    lift: 'Available',
    security: 'cctv cameras',
    powerBackup: 'Available',
    facing: 'East Facing',
    propertyAge: 1,
    waterSupply: 'Regular',
    nearbyLocation: 'The Shri Ram Universal School',
    nearbyMetro: 'Raidurg metro station',
    nearbyMall: 'Sarath City Capital Mall ',
    latitude:'17.419689285304486',
    longitude:'78.33823623821539',
    discount: '8% off on annual rent',
},

];
