
export const houses = [
  {
    id: 1,
    title: 'Urban Tuplis 10th Floor',
    location: 'L.B Nagar ,Hyderabad ,500079',
    image: '/images/img6.jpeg',
    beds: 2,
    size: '1600 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 15000,
    discount: '15% OFF for 1st 3 months',
  },
  {
    id: 2,
    title: 'Tuplis 12th Floor',
    location: 'S.R Nagar ,Hyderabad ,50089',
    image: '/images/img2.jpeg',
    beds: 2,
    size: '1800 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 16000,
    discount: '15% OFF for 1st 3 months',
  },
  {
    id: 3,
    title: 'Avanthi Hills 5th Floor',
    location: 'BalaNagar ,Hyderabad ,500071',
    image: '/images/img3.jpeg',
    beds: 2,
    size: '1400 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 12000,
    discount: '15% OFF for 1st 3 months',
  },
  {
    id: 4,
    title: 'Vassavi Estate 2nd Floor',
    location: 'R.N.Reddy ,Hyderabad ,500079',
    image: '/images/img4.jpg',
    beds: 2,
    size: '1600 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 10000,
    discount: '15% OFF for 1st 3 months',
  },
  {
    id: 5,
    title: 'Sun City My Homes 10th Floor',
    location: 'ShadNagar ,Hyderabad ,500079',
    image: '/images/img5.jpg',
    beds: 2,
    size: '1600 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 20000,
    discount: '15% OFF for 1st 3 months',
  },

  {
    id: 6,
    title: 'Sun City My Homes 10th Floor',
    location: 'ShadNagar ,Hyderabad ,500079',
    image: '/images/img5.jpg',
    beds: 2,
    size: '1600 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 20000,
    discount: '15% OFF for 1st 3 months',
  },
  {
    id: 7,
    title: 'Sun City My Homes 10th Floor',
    location: 'ShadNagar ,Hyderabad ,500079',
    image: '/images/img5.jpg',
    beds: 2,
    size: '1600 Sq Ft',
    vehicles: '2 2W+1 4W',
    type: 'Flat',
    price: 20000,
    discount: '15% OFF for 1st 3 months',
  },
];
